insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Xiaxi');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Datan');
insert into countries (c_name, country_code, capital) values ('Poland', 'PL', 'Ojrzeń');
insert into countries (c_name, country_code, capital) values ('Poland', 'PL', 'Stryków');
insert into countries (c_name, country_code, capital) values ('Mexico', 'MX', 'Jose Maria Morelos');
insert into countries (c_name, country_code, capital) values ('Bulgaria', 'BG', 'Chavdar');
insert into countries (c_name, country_code, capital) values ('Ukraine', 'UA', 'Dubno');
insert into countries (c_name, country_code, capital) values ('Bosnia and Herzegovina', 'BA', 'Starcevica');
insert into countries (c_name, country_code, capital) values ('Paraguay', 'PY', 'Pilar');
insert into countries (c_name, country_code, capital) values ('Nigeria', 'NG', 'Zaria');
insert into countries (c_name, country_code, capital) values ('Russia', 'RU', 'Vakhrushi');
insert into countries (c_name, country_code, capital) values ('Russia', 'RU', 'Kadyy');
insert into countries (c_name, country_code, capital) values ('Czech Republic', 'CZ', 'Trnava');
insert into countries (c_name, country_code, capital) values ('Guatemala', 'GT', 'Santa Lucía Cotzumalguapa');
insert into countries (c_name, country_code, capital) values ('Russia', 'RU', 'Sosnovyy Bor');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Baiyun');
insert into countries (c_name, country_code, capital) values ('Indonesia', 'ID', 'Kamalaputi');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Suhong');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Beisijia');
insert into countries (c_name, country_code, capital) values ('Ecuador', 'EC', 'La Libertad');
insert into countries (c_name, country_code, capital) values ('Indonesia', 'ID', 'Karangsonojabon');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Lümeng');
insert into countries (c_name, country_code, capital) values ('Germany', 'DE', 'Köln');
insert into countries (c_name, country_code, capital) values ('Democratic Republic of the Congo', 'CD', 'Inongo');
insert into countries (c_name, country_code, capital) values ('Portugal', 'PT', 'Capela');
insert into countries (c_name, country_code, capital) values ('Azerbaijan', 'AZ', 'Shamkhor');
insert into countries (c_name, country_code, capital) values ('Russia', 'RU', 'Moshenskoye');
insert into countries (c_name, country_code, capital) values ('Indonesia', 'ID', 'Babakan');
insert into countries (c_name, country_code, capital) values ('France', 'FR', 'Creil');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Jiasi');
insert into countries (c_name, country_code, capital) values ('Indonesia', 'ID', 'Jedung');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Jiekou');
insert into countries (c_name, country_code, capital) values ('Nigeria', 'NG', 'Abonnema');
insert into countries (c_name, country_code, capital) values ('Portugal', 'PT', 'Agra');
insert into countries (c_name, country_code, capital) values ('Jamaica', 'JM', 'Malvern');
insert into countries (c_name, country_code, capital) values ('Kazakhstan', 'KZ', 'Sarkand');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Tiechang');
insert into countries (c_name, country_code, capital) values ('Philippines', 'PH', 'San Martin');
insert into countries (c_name, country_code, capital) values ('Kuwait', 'KW', 'Al Farwānīyah');
insert into countries (c_name, country_code, capital) values ('Colombia', 'CO', 'San Juan del Cesar');
insert into countries (c_name, country_code, capital) values ('Russia', 'RU', 'Ozëry');
insert into countries (c_name, country_code, capital) values ('Jamaica', 'JM', 'Savanna-la-Mar');
insert into countries (c_name, country_code, capital) values ('France', 'FR', 'Paris 14');
insert into countries (c_name, country_code, capital) values ('Kazakhstan', 'KZ', 'Taldykorgan');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Xingxi');
insert into countries (c_name, country_code, capital) values ('Indonesia', 'ID', 'Medan');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Longtian');
insert into countries (c_name, country_code, capital) values ('China', 'CN', 'Zhifudao');
insert into countries (c_name, country_code, capital) values ('Japan', 'JP', 'Bihoro');
